A10_Usu/urls.py
from django.urls import path
from .views import *
# from django.views.generic import LogoutView

app_name = 'A10_Usu'

urlpatterns = [
    path('', home, name='home'),
    path('registro_paciente/', registro_paciente, name='registro_paciente'),
    path('mensaje_verificacion_enviado/', mensaje_verificacion_enviado, name='mensaje_verificacion_enviado'),
    path('verificar_cuenta/<str:uidb64>/<str:token>/', verificar_cuenta, name='verificar_cuenta'),
    path('completar_perfil_paciente/<int:paciente_id>/', completar_perfil_paciente, name='completar_perfil_paciente'),
    path('listar_pacientes/', listar_pacientes, name='listar_pacientes'),

    path('usuarios/', usuarios, name='usuarios'),
    path('registro_usuario/', registro_usuario, name='registro_usuario'),
    path('completar_perfil_jefe_plataforma/<int:jefe_plataforma_id>/', completar_perfil_jefe_plataforma, name='completar_perfil_jefe_plataforma'),
    path('completar_perfil_recepcionista/<int:recepcionista_id>/', completar_perfil_recepcionista, name='completar_perfil_recepcionista'),
    path('completar_perfil_medico/<int:medico_id>/', completar_perfil_medico, name='completar_perfil_medico'),
    path('ver_perfilout/<int:user_id>/', ver_perfilout, name='ver_perfilout'),
    # path('registro_jefe_plataforma/', registro_jefe_plataforma, name='registro_jefe_plataforma'),
    # path('registro_recepcionista/', registro_recepcionista, name='registro_recepcionista'),

    path('cambiar_rol/',cambiar_rol,name='cambiar_rol'),

    path('vista_parametros/', vista_parametros, name='vista_parametros'),
    path('registro_genero/', registro_genero, name='registro_genero'),
    path('registro_especialidad', registro_especialidad, name='registro_especialidad'),
    path('registro_sistema_salud/', registro_sistema_salud, name='registro_sistema_salud'),
    path('registroExamen/', registroExamen, name='registroExamen'),
    path('registroMedicamento/', registroMedicamento, name='registroMedicamento'),
    path('medicamento/<int:pk>/', medicamentoVer, name='medicamentoVer'),
    path('medicamento/editar/<int:pk>/', medicamentoEditar, name='medicamentoEditar'),

]

A30_Fic/urls.py
from django.urls import path
from .views import *
# from django.views.generic import LogoutView

app_name = 'A30_Fic'

urlpatterns = [

    path('listar_pacientes_con_horas/', listar_pacientes_con_horas, name='listar_pacientes_con_horas'),
    path('iniciar_ficha_medica/<int:paciente_id>/', iniciar_ficha_medica, name='iniciar_ficha_medica'),
    path('iniciar_ficha_hora/<int:hora_id>/', iniciar_ficha_hora, name='iniciar_ficha_hora'),
    path('listar_fichas_medicas_ajax/', listar_fichas_medicas_ajax, name='listar_fichas_medicas_ajax'),
    path('listar_fichas_medicas/', listar_fichas_medicas, name='listar_fichas_medicas'),
    path('listar_mis_fichas_medicas/', listar_mis_fichas_medicas, name='listar_mis_fichas_medicas'),
    path('ver_ficha_medica/<int:ficha_id>/', ver_ficha_medica, name='ver_ficha_medica'),
    path('modificar_ficha_medica/<int:ficha_id>/', modificar_ficha_medica, name='modificar_ficha_medica'),
    path('reasignar_ficha_medica/<int:ficha_id>/', reasignar_ficha_medica, name='reasignar_ficha_medica'),
    path('historial_medico/<int:paciente_id>/', historial_medico, name='historial_medico'),
]

Med/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from A10_Usu.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),

    path('accounts/', include('allauth.urls')),

    # path('accounts/signup/paciente/', registro_paciente, name='registro_paciente'),
    # path('accounts/signup/registro_jefe_plataforma/',registro_jefe_plataforma, name='registro_jefe_plataforma'),

    path('accounts/redireccion_despues_login/', redireccion_despues_login, name='redireccion_despues_login'),
    path('accounts/seleccionar_tipo_registro/', seleccionar_tipo_registro, name='seleccionar_tipo_registro'),

    path('accounts/completar_perfil_paciente/', completar_perfil_paciente, name='completar_perfil_paciente'),
    # path('accounts/email-confirmation/<key>/', CustomConfirmEmailView.as_view(), name='account_confirm_email'),
    # path('accounts/completar_perfil_jefe_plataforma/', completar_perfil_jefe_plataforma, name='completar_perfil_jefe_plataforma'),


    # path('accounts/signup/recepcionista/', registro_recepcionista, name='registro_recepcionista'),
    # path('accounts/signup/medico/', registro_medico, name='registro_medico'),
    path('gestion_usuarios/', include('A10_Usu.urls', namespace='Usuarios')),
    path('horas_medicas/', include('A20_Hrs.urls', namespace='Horas Medicas')),
    path('fichas_medicas/', include('A30_Fic.urls',namespace='Fichas Medicas')),
    path('consultas/', include('A31_Con.urls',namespace='Consultas')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

A30_Fic/models.py
from django.db import models
from A10_Usu.models import *

class FichaMedica(models.Model):
    paciente        = models.ForeignKey(Paciente, on_delete=models.CASCADE, related_name='paciente_fichas')
    medico          = models.ForeignKey(Medico, on_delete=models.CASCADE, related_name='medico_fichas')
    f_consulta      = models.DateTimeField(auto_now_add=True)
    temperatura     = models.FloatField()
    p_sistolica     = models.IntegerField()
    p_diastolica    = models.IntegerField()
    altura          = models.FloatField(default=0.0)
    peso            = models.FloatField(default=0.0)
    imc             = models.FloatField(blank=True, null=True, default=0.0)
    sintomas        = models.TextField(blank=True, null=True, default='Sin síntomas')
    diagnostico     = models.TextField()
    prescripcion    = models.TextField()
    notas           = models.TextField(blank=True, null=True)
    estado          = models.CharField(max_length=20, choices=[('NoIniciada','No Iniciada'),('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='NoIniciada')

    class Meta:
        verbose_name        = 'Ficha Médica'
        verbose_name_plural = 'Fichas Médicas'
        ordering            = ["f_consulta","estado"]

    def __str__(self):
        return f'Ficha Médica {self.id} [{self.f_consulta}/{self.estado}] [{self.medico}/{self.paciente}]'

    # def imc(self):
    #     if self.altura and self.peso:
    #         return round(self.peso/(self.altura**2),2)
    #     return None

A30_Fic/forms.py
from django import forms
from .models import *

class RegistroFichaMedicaForm(forms.ModelForm):
    class Meta:
        model = FichaMedica
        fields = '__all__'
        widgets = {
            'medico'    : forms.Select(),
            'paciente'  : forms.Select(),
            'f_consulta': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'estado': forms.Select(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')]),
            }

A30_Fic/views.py
from django.urls import reverse
from .forms import *
from A20_Hrs.models import HoraMedica, Medico, Paciente
from django.contrib import messages
from datetime import datetime, date
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404 as go404
from icecream import ic

import io
import json
import matplotlib.pyplot as plt
import pdb
import time
import urllib, base64





@login_required
def listar_pacientes_con_horas(request):
    if (request.user.groups.filter(name__in=['Jefes de Plataforma', 'Recepcionista']).exists() or request.user.is_superuser):
        horas_medicas=HoraMedica.objects.filter(estado='tomada').select_related('paciente') #

    elif request.user.groups.filter(name__in=['Medicos']).exists():
        medico = go404(Medico, user=request.user)
        horas_medicas = HoraMedica.objects.filter(medico=medico, estado='tomada').select_related('paciente')

    return render(request, 'A30_Fic/listar_pacientes_con_horas.html', {
        'horas_medicas': horas_medicas,
    })

@login_required
def iniciar_ficha_medica(request, paciente_id):
    medico = go404(Medico, user=request.user)
    user =go404(CustomUser, id=paciente_id)
    paciente = go404(Paciente, user=user.id)
    now = datetime.now()

    if request.method == 'POST':
        altura = request.POST['altura']
        peso = request.POST['peso']
        imc = request.POST.get('imc') # Obtener el IMC calculado en el cliente
        notas = request.POST.get('notas', '')

        FichaMedica.objects.create(
            paciente=paciente,
            medico=medico,
            temperatura=request.POST['temperatura'],
            p_sistolica=request.POST['p_sistolica'],
            p_diastolica=request.POST['p_diastolica'],
            altura=request.POST['altura'],
            peso=request.POST['peso'],
            diagnostico=request.POST['diagnostico'],
            prescripcion=request.POST['prescripcion'],
            imc=imc,
            notas=notas,
            estado='Abierta'
        )
        messages.success(request, "Ficha médica iniciada exitosamente.")
        return redirect('A30_Fic:listar_fichas_medicas')

    return render(request, 'A30_Fic/iniciar_ficha_medica.html', locals())


@login_required
def iniciar_ficha_hora(request, hora_id):
    try:
        hora = go404(HoraMedica, pk = hora_id)
        medico = go404(Medico, pk = hora.medico.pk)
        paciente = go404(Paciente, pk = hora.paciente.pk)
        action_url = reverse('A30_Fic:iniciar_ficha_hora',args=[str(hora_id)])
        now = datetime.now()

        if request.method == 'POST':  # Mueve la creación de la ficha DENTRO del bloque POST
            altura = request.POST['altura']
            peso = request.POST['peso']
            imc = request.POST.get('imc')
            notas = request.POST.get('notas', '')
            temperatura = request.POST.get('temperatura')
            p_sistolica = request.POST.get('p_sistolica')
            p_diastolica = request.POST.get('p_diastolica')
            diagnostico = request.POST.get('diagnostico')
            prescripcion = request.POST.get('prescripcion')
            sintomas = request.POST.get('sintomas')

            FichaMedica.objects.create(
                paciente=paciente,
                medico=medico,
                temperatura=temperatura,
                p_sistolica=p_sistolica,
                p_diastolica=p_diastolica,
                altura=altura,
                peso=peso,
                imc=imc,
                sintomas=sintomas,
                diagnostico=diagnostico,
                prescripcion=prescripcion,
                notas=notas,
                estado='Abierta',
            )
            hora.estado = 'iniciada'
            hora.save()

            messages.success(request, "Ficha médica iniciada exitosamente.")
            return redirect('A20_Hrs:calendario_horasmedicas')
        elif request.method == 'GET':
            return render(request, 'A30_Fic/iniciar_ficha_medica.html', locals())

    except HoraMedica.DoesNotExist:
        messages.error(request, "La hora médica solicitada no existe.")
        return redirect('A20_Hrs:calendario_horasmedicas')


@login_required
def listar_fichas_medicas_ajax(request):
    if request.user.groups.filter(name__in=['Jefes de Plataforma', 'Recepcionista']).exists() or request.user.is_superuser:# Solo jefes de plataforma y superusuarios pueden listar todas las fichas médicas (de todos los pacientes)
        fichas_medicas = FichaMedica.objects.all()
        time.sleep(3) # Simula el proceso interno (¡ahora no bloquea!)
        html_content = render(request, 'A30_Fic/listar_fichas_medicas_tabla.html', {'fichas_medicas': fichas_medicas}).content.decode('utf-8')
        ic(request.user  )
        return JsonResponse({'html': html_content})
    elif request.user.groups.filter(name__in=['Medicos']).exists():
        medico = go404(Medico, user=request.user)
        fichas_medicas = FichaMedica.objects.filter(medico=medico)
        time.sleep(3) # Simula el proceso interno (¡ahora no bloquea!)
        html_content = render(request, 'A30_Fic/listar_fichas_medicas_tabla.html', {'fichas_medicas': fichas_medicas}).content.decode('utf-8')
        return JsonResponse({'html': html_content})
    elif request.user.groups.filter(name__in=['Pacientes']).exists():
        paciente = go404(Paciente, user=request.user)
        fichas_medicas = FichaMedica.objects.filter(paciente=paciente, estado='Cerrada')
        time.sleep(3) # Simula el proceso interno (¡ahora no bloquea!)
        html_content = render(request, 'A30_Fic/listar_fichas_medicas_tabla.html', {'fichas_medicas': fichas_medicas}).content.decode('utf-8')
        return JsonResponse({'html': html_content})
    else:
        return JsonResponse({'error': 'No tienes permiso para acceder a esta página.'}, status=403)

@login_required
def listar_fichas_medicas(request):
    return render(request, 'A30_Fic/listar_fichas_medicas.html')


@login_required
def listar_mis_fichas_medicas(request):

    if request.user.is_superuser:
        messages.info(request, "Acceso a superusuario")
    elif request.user.groups.filter(name__in=['Medicos']).exists():
        medico = go404(Medico, user=request.user)
        fichas_medicas = FichaMedica.objects.filter(medico=medico)
        messages.info(request, "Acceso a medico")
    else:
        messages.error(request, "No tienes permiso para modificar esta ficha médica.")
        return redirect('A30_Fic:listar_fichas_medicas')

    return render(request, 'A30_Fic/listar_mis_fichas_medicas.html', {
        'fichas_medicas': fichas_medicas,
    })


@login_required
def ver_ficha_medica(request, ficha_id):

    try:
        ficha = go404(FichaMedica, id=ficha_id)
        sus_especialidades = ficha.medico.especialidad.all()
        messages.info(request, "Ver ficha médica de " + str(ficha.paciente))
    except FichaMedica.DoesNotExist:    # Si no existe la ficha médica
        messages.error(request, "La ficha médica solicitada no existe.")

    if request.user.is_superuser:
        messages.info(request, "Modificando ficha médica de " + str(ficha.paciente))
    elif request.user.groups.filter(name__in=['Medicos']).exists():
        medico = go404(Medico, user=request.user)
        messages.info(request, "Modificando ficha médica de " + str(ficha.paciente))
    elif request.user.groups.filter(name__in=['Pacientes']).exists():
        messages.info(request, "Ver ficha médica de " + str(ficha.paciente))
        return render(request, 'A30_Fic/ver_ficha_medica.html',locals())
    else:
        messages.error(request, "No tienes permiso para modificar esta ficha médica.")
        return redirect('A30_Fic:listar_fichas_medicas')


    if request.method == 'POST':
        ficha.temperatura = float(request.POST['temperatura'].replace(',', '.'))
        ficha.p_sistolica = int(request.POST['p_sistolica'])
        ficha.p_diastolica = int(request.POST['p_diastolica'])
        ficha.altura = float(request.POST['altura'].replace(',', '.'))
        ficha.peso = float(request.POST['peso'].replace(',', '.'))
        ficha.diagnostico = request.POST['diagnostico']
        ficha.prescripcion = request.POST['prescripcion']
        ficha.notas = request.POST.get('notas', '')
        ficha.estado = request.POST['estado']
        ficha.save()
        messages.success(request, "Ficha médica modificada exitosamente.")
        return redirect('A30_Fic:listar_fichas_medicas')

    return render(request, 'A30_Fic/modificar_ficha_medica.html', {
        'ficha': ficha,
    })


@login_required
def modificar_ficha_medica(request, ficha_id):
    ficha = go404(FichaMedica, id=ficha_id)

    if request.user.is_superuser:
        messages.info(request, "Modificando ficha médica de " + str(ficha.paciente))
    elif request.user.groups.filter(name__in=['Medicos']).exists():
        medico = go404(Medico, user=request.user)
        messages.info(request, "Modificando ficha médica de " + str(ficha.paciente))
    else:
        messages.error(request, "No tienes permiso para modificar esta ficha médica.")
        return redirect('A30_Fic:listar_fichas_medicas')

    if request.method == 'POST':
        ficha.temperatura = float(request.POST['temperatura'].replace(',', '.'))
        ficha.p_sistolica = int(request.POST['p_sistolica'])
        ficha.p_diastolica = int(request.POST['p_diastolica'])
        ficha.altura = float(request.POST['altura'].replace(',', '.'))
        ficha.peso = float(request.POST['peso'].replace(',', '.'))
        ficha.diagnostico = request.POST['diagnostico']
        ficha.prescripcion = request.POST['prescripcion']
        ficha.notas = request.POST.get('notas', '')
        ficha.estado = request.POST['estado']

templates/A30_Fic/historial_medico.html
{% extends 'base.html' %}

{% block content %}
<h1>Historial Médico de {{ paciente.user.first_name }} {{ paciente.user.last_name }}</h1>

<h2>Historial de Atenciones</h2>
{% if fichas_medicas %}
    <ul>
        {% for ficha in fichas_medicas %}
            <li>
                {{ ficha.f_consulta|date:"l, d/m/Y H:i" }} - {{ ficha.diagnostico }} -
                <a href="{% url 'A30_Fic:ver_ficha_medica' ficha.id %}">Ver Ficha</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay fichas médicas disponibles.</p>
{% endif %}

<h2>Histograma de Pesos y Estatura</h2>
<canvas id="pesoAlturaChart" style="width: 100%; height: 400px;"></canvas>

<h2>Gráfico de Presiones Sistólicas y Diastólicas</h2>
<img src="data:image/png;base64,{{ grafico_presiones }}" alt="Gráfico de Presiones Sistólicas y Diastólicas">

<h2>Últimos Medicamentos</h2>
<ul>
    {% for medicamento in medicamentos %}
        <li>{{ medicamento }}</li>
    {% endfor %}
</ul>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctxPesoAltura = document.getElementById('pesoAlturaChart').getContext('2d');
    var pesoAlturaChart = new Chart(ctxPesoAltura, {
        type: 'bar',
        data: {
            labels: {{ fechas|safe }},
            datasets: [
                {
                    label: 'Peso (kg)',
                    data: {{ pesos|safe }},
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                },
                {
                    label: 'Altura (cm)',
                    data: {{ alturas|safe }},
                    backgroundColor: 'rgba(255, 206, 86, 0.2)',
                    borderColor: 'rgba(255, 206, 86, 1)',
                    borderWidth: 1
                }
            ]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>

{% endblock %}

templates/A30_Fic/listar_fichas_medicas.html
{% extends 'base.html' %}

{% block content %}
<h1>Listado General De Fichas Médicas</h1>

<div class="d-flex justify-content-center">
    <div id="spinner" class="spinner-border text-danger" role="status" style="display: none;">
        <span class="visually-hidden">Loading...</span>
    </div>
</div>

<div id="contenido_principal">  </div>

{% for group in request.user.groups.all %}

    {% if group.name == "Jefes de Plataforma" or request.user.is_superuser %}
        <div id="jefe_plataforma_content" style="display: none;">
        {% if fichas_medicas %}
            <ul>
                {% for ficha in fichas_medicas %}
                    <li>
                        {{ ficha.id }})&nbsp;&nbsp; {{ ficha.medico }} / {{ ficha.paciente }} - {{ ficha.f_consulta|date:"l, d/m/Y H:i" }} [ {{ ficha.estado }} ]
                        &nbsp;<a href="{% url 'A30_Fic:reasignar_ficha_medica' ficha.id %}">Reasignar</a>
                    </li>
                {% endfor %}
            </ul>
        {% comment %} {% else %}
            <p>No tienes fichas médicas.</p> {% endcomment %}
        {% endif %}
        </div>
    {% endif %}

    {% if group.name == "Pacientes" %}
        <div id="pacientes_content" style="display: none;">
        {% if fichas_medicas %}
            <ul>
                {% for ficha in fichas_medicas %}
                    <li>
                        {{ ficha.id }})&nbsp;&nbsp; {{ ficha.medico }} / {{ ficha.paciente }} - {{ ficha.f_consulta|date:"l, d/m/Y H:i" }} [ {{ ficha.estado }} ]
                        &nbsp;<a href="{% url 'A30_Fic:ver_perfilout' user.id %}">Ver perfil del paciente</a>
                    </li>
                {% endfor %}
            </ul>
        {% comment %} {% else %}
            <p>No tienes fichas médicas.</p> {% endcomment %}
        {% endif %}
        </div>
    {% endif %}

{% endfor %}

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function() {
        $("#spinner").show(); // Mostrar el spinner inmediatamente

        $.ajax({
            url: '/fichas_medicas/listar_fichas_medicas_ajax/', // URL para la vista AJAX (ver abajo)
            type: 'GET',
            success: function(data) {
                console.log("Respuesta AJAX:", data); // Imprime la respuesta en la consola
                $("#spinner").hide(); // Ocultar el spinner cuando la respuesta llega
                $("#contenido_principal").html(data.html);
                $("#jefe_plataforma_content").html($("#jefe_plataforma_content", data.html).html())
                $("#pacientes_content").html($("#pacientes_content", data.html).html())
                $("#jefe_plataforma_content").show();
                $("#pacientes_content").show();

            },
            error:function(xhr,status,error) {
                console.error("Error en la llamada AJAX:", status, error); // Imprime errores en la consola
                $("#spinner").hide(); // Oculta el spinner incluso en caso de error
                $("#contenido_principal").html("<p>Ocurrió un error al cargar los datos.</p>"); // Muestra un mensaje de error
            },
        });
    });
</script>

{% endblock %}

templates/A30_Fic/listar_fichas_medicas_tabla.html
{% if request.user.is_superuser %}
    {% if fichas_medicas %}
        <ul mt-4>
            {% for ficha in fichas_medicas %}
                <li>
                    {{ ficha.id }})&nbsp;&nbsp; {{ ficha.medico }} / {{ ficha.paciente }} - {{ ficha.f_consulta|date:"l, d/m/Y H:i" }} [ {{ ficha.estado }} ]
                    &nbsp;<a href="{% url 'A30_Fic:reasignar_ficha_medica' ficha.id %}">Reasignar</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        }<p>No tienes fichas médicas.</p>
    {% endif %}
{% endif %}

{% for group in request.user.groups.all %} {# Iteramos sobre los grupos del usuario #}
    {% if group.name == "Jefes de Plataforma" %} {# Si el usuario pertenece al grupo "Jefes de Plataforma" #}
        {% if fichas_medicas %}
            <ul mt-4>
                {% for ficha in fichas_medicas %}
                    <li>
                        {{ ficha.id }})&nbsp;&nbsp; {{ ficha.medico }} / {{ ficha.paciente }} - {{ ficha.f_consulta|date:"l, d/m/Y H:i" }} [ {{ ficha.estado }} ]
                        &nbsp;<a href="{% url 'A30_Fic:reasignar_ficha_medica' ficha.id %}">Reasignar</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No tienes fichas médicas.</p>
        {% endif %}
    {% endif %}


    {% if group.name == "Pacientes" %}
        {% if fichas_medicas %}
            <ul>
                {% for ficha in fichas_medicas %}
                    <li>
                        {{ ficha.f_consulta|date:"l, d/m/Y H:i" }}&nbsp;&nbsp; {{ ficha.medico }} &nbsp;&nbsp;-&nbsp;&nbsp;  [ {{ ficha.estado }} ]
                        &nbsp;<a class="btn btn-primary" href="{% url 'A30_Fic:ver_ficha_medica' ficha.id %}">Ver</a>
                        &nbsp;<a href="{% url 'A30_Fic:ver_perfilout' user.id %}">Ver tu ficha</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No tienes fichas médicas.</p>
        {% endif %}
    {% endif %}
{% endfor %}

templates/A30_Fic/listar_mis_fichas_medicas.html
{% extends 'base.html' %}

{% block content %}
<h1>Mis Fichas Médicas</h1>

{% if fichas_medicas %}
    <ul>
        {% for ficha in fichas_medicas %}
            <li>
                {{ ficha.f_consulta|date:"l, d/m/Y H:i" }} - {{ ficha.estado }} -
                <a href="{% url 'A30_Fic:modificar_ficha_medica' ficha.id %}">Modificar</a>
                <a href="{% url 'A30_Fic:reasignar_ficha_medica' ficha.id %}">Reasignar</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No tienes fichas médicas.</p>
{% endif %}
{% endblock %}

templates/A30_Fic/listar_pacientes_con_horas.html
{% extends 'base.html' %}

{% block content %}
<h1>Pacientes con Horas Asignadas</h1>
{% if horas_medicas %}
    <ul>
        {% for hora_medica in horas_medicas %}
            <li>
                {{ hora_medica.paciente.user.first_name }} {{ hora_medica.paciente.user.last_name }} -
                <a href="{% url 'A30_Fic:iniciar_ficha_medica' hora_medica.paciente.user.id %}">Iniciar Ficha Médica</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay pacientes con horas asignadas.</p>
{% endif %}
{% endblock %}

templates/A30_Fic/reasignar_ficha_medica.html
{% extends 'base.html' %}

{% block content %}
<h1>Reasignar Ficha Médica</h1>

<form method="POST">
    {% csrf_token %}
    <label for="medico">Nuevo Médico:</label>
    <select id="medico" name="medico" required>
        {% for medico in medicos %}
            <option value="{{ medico.id }}">{{ medico.user.first_name }} {{ medico.user.last_name }}</option>
        {% endfor %}
    </select><br>
    <button type="submit">Reasignar Ficha Médica</button>
</form>

{% endblock %}

templates/A30_Fic/registro_ficha_medica.html
{% extends 'base.html' %}

{% block content %}
<h2>Registro Ficha Medica</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Grabar</button>
</form>
{% endblock %}