A31_Con/urls.py
from django.urls import path
from .views import *
# from django.views.generic import LogoutView

app_name = 'A31_Con'

urlpatterns = [
    path('consultas_ajax/', consultas_ajax, name='consultas_ajax'),
    path('consultas/', consultas, name='consultas'),
    path('consulta_iniciar/<int:hora_id>/', consulta_iniciar, name='consulta_iniciar'),
    path('consulta_detalle/<int:consulta_id>/', consulta_detalle, name='consulta_detalle'),
    path('enviar_resultados_al_medico/<int:consulta_id>/', enviar_resultados_al_medico, name='enviar_resultados_al_medico'),
    path('consulta_editar/<int:consulta_id>/', consulta_editar, name='consulta_editar'),

    path('examen/<int:examen_id>/subir/', subir_resultado_examen, name='subir_resultado_examen'),
    path('examen/<int:examen_id>/bajar/', bajar_resultado_examen, name='bajar_resultado_examen'),

    path('obtener_medicamentos_seleccionados/', obtener_medicamentos_seleccionados, name='obtener_medicamentos_seleccionados'),
    path('imprimir_orden_examen/<int:consulta_id>/', imprimir_orden_examen, name='imprimir_orden_examen'),
    path('imprimir_prescripcion/<int:consulta_id>/', imprimir_prescripcion, name='imprimir_prescripcion'),
    path('imprimir_certificado/<int:consulta_id>/', imprimir_certificado, name='imprimir_certificado'),
    path('enviar_email_certificado/<int:consulta_id>/', enviar_email_certificado, name='enviar_email_certificado'),


    path('consulta_informes/', consulta_informes, name='consulta_informes'),
    path('informe_historico/<int:paciente_id>/',informe_historico, name='informe_historico'),
    path('consultas_resumen/<int:paciente_id>/',consultas_resumen, name='consultas_resumen'),


]

Med/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from A10_Usu.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),

    path('accounts/', include('allauth.urls')),

    # path('accounts/signup/paciente/', registro_paciente, name='registro_paciente'),
    # path('accounts/signup/registro_jefe_plataforma/',registro_jefe_plataforma, name='registro_jefe_plataforma'),

    path('accounts/redireccion_despues_login/', redireccion_despues_login, name='redireccion_despues_login'),
    path('accounts/seleccionar_tipo_registro/', seleccionar_tipo_registro, name='seleccionar_tipo_registro'),

    path('accounts/completar_perfil_paciente/', completar_perfil_paciente, name='completar_perfil_paciente'),
    # path('accounts/email-confirmation/<key>/', CustomConfirmEmailView.as_view(), name='account_confirm_email'),
    # path('accounts/completar_perfil_jefe_plataforma/', completar_perfil_jefe_plataforma, name='completar_perfil_jefe_plataforma'),


    # path('accounts/signup/recepcionista/', registro_recepcionista, name='registro_recepcionista'),
    # path('accounts/signup/medico/', registro_medico, name='registro_medico'),
    path('gestion_usuarios/', include('A10_Usu.urls', namespace='Usuarios')),
    path('horas_medicas/', include('A20_Hrs.urls', namespace='Horas Medicas')),
    path('fichas_medicas/', include('A30_Fic.urls',namespace='Fichas Medicas')),
    path('consultas/', include('A31_Con.urls',namespace='Consultas')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

A31_Con/views.py
import os

from .models import *
from A20_Hrs.models import HoraMedica, Medico, Paciente
from datetime import datetime, date, timedelta
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail,EmailMultiAlternatives
from django.http import HttpResponse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404 as go404
from django.urls import reverse
from django.utils import timezone
from email.message import EmailMessage
from fpdf import FPDF  # Importa FPDF
from icecream import ic
from matplotlib.widgets import Cursor

import io, base64, urllib.parse
import json
import logging
import matplotlib.pyplot as plt
import pandas as pd
import pdb
import time
import traceback
import urllib, base64
import numpy as np
from scipy.interpolate import interp1d

logger = logging.getLogger('envio_email')

# Create your views here.

@login_required
def consultas_ajax(request):
    user = request.user
    consultas = Consulta.objects.none()  # Inicializa un queryset vacío
    if request.user.groups.filter(name__in=['Jefes de Plataforma', 'Recepcionista']).exists() or request.user.is_superuser:
        consultas = Consulta.objects.all()

    elif request.user.groups.filter(name__in=['Medicos']).exists():
        medico = go404(Medico, user=user)
        consultas = Consulta.objects.filter(hora_medica__medico=medico) # Filtra las consultas del médico logueado

    elif request.user.groups.filter(name__in=['Pacientes']).exists():
        paciente = go404(Paciente, user=user)
        consultas = Consulta.objects.filter(hora_medica__paciente=paciente) # Filtra las consultas del paciente logueado que estén finalizadas
    else:
        messages.error(request, 'No tiene permisos para ver esta página')
        return HttpResponseRedirect(reverse('home'))

    time.sleep(2) # Simula el proceso interno (¡ahora no bloquea!)
    html_content = render(request, 'A31_Con/consultas_ajax.html', {'consultas': consultas}).content.decode('utf-8')
    return JsonResponse({'html': html_content})

@login_required
def consultas(request):
    return render(request, 'A31_Con/consultas.html')


@login_required
def consulta_iniciar(request, hora_id):
    try:
        hora = go404(HoraMedica, pk=hora_id)
        if not hora.pagada or hora.estado != 'pagada':
            messages.error(request, "La hora médica no está pagada.")
            return redirect('A20_Hrs:calendario_horasmedicas')
        medico = go404(Medico, pk=hora.medico.pk)
        paciente = go404(Paciente, pk=hora.paciente.pk)

        now = timezone.now()
        if hora.f_hra < now:
            messages.error(request, "No se puede iniciar una consulta para una hora médica pasada.")
            return redirect('A20_Hrs:calendario_horasmedicas')

        examenes = Examen.objects.all()
        medicamentos = Medicamento.objects.filter(estado='activo')  # Obtén los medicamentos activos

        # Manejo de la selección de medicamentos con AJAX
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            if 'seleccionar_medicamento' in request.GET:
                medicamento_id = request.GET['seleccionar_medicamento']
                if 'medicamentos_seleccionados' not in request.session:
                    request.session['medicamentos_seleccionados'] = []
                if medicamento_id not in request.session['medicamentos_seleccionados']:
                    request.session['medicamentos_seleccionados'].append(medicamento_id)
                request.session.modified = True
                return JsonResponse({'status': 'ok'})
            elif 'deseleccionar_medicamento' in request.GET:
                medicamento_id = request.GET['deseleccionar_medicamento']
                if 'medicamentos_seleccionados' in request.session:
                    if medicamento_id in request.session['medicamentos_seleccionados']:
                        request.session['medicamentos_seleccionados'].remove(medicamento_id)
                    request.session.modified = True
                return JsonResponse({'status': 'ok'})

        # Obtener medicamentos seleccionados de la sesión
        medicamentos_seleccionados_ids = request.session.get('medicamentos_seleccionados', [])
        medicamentos_seleccionados = Medicamento.objects.filter(id__in=medicamentos_seleccionados_ids)

        if hora.pagada and hora.f_hra.date() == now.date():  # Verifica si está pagada y es hoy

            if request.method == 'POST':
                # Guardar datos del formulario en la sesión
                consulta_data = request.session.get('consulta_data', {})
                consulta_data.update({
                    'temperatura': request.POST.get('temperatura'),
                    'p_sistolica': request.POST.get('p_sistolica'),
                    'p_diastolica': request.POST.get('p_diastolica'),
                    'altura': request.POST.get('altura'),
                    'peso': request.POST.get('peso'),
                    'imc': request.POST.get('imc'),
                    'notas': request.POST.get('notas'),
                    'sintomas': request.POST.get('sintomas'),
                    'diagnostico': request.POST.get('diagnostico'),
                    'observaciones': request.POST.get('observaciones'),
                    'examenes': request.POST.getlist('examenes'),
                    'lugar_emision': request.POST.get('lugar_emision'),
                    'dirigido_a': request.POST.get('dirigido_a'),
                    'antecedentes': request.POST.get('antecedentes'),
                    'diagnosis': request.POST.get('diagnosis'),
                    'inicio': request.POST.get('inicio'),
                    'termino': request.POST.get('termino'),
                })
                request.session['consulta_data'] = consulta_data
                request.session.modified = True

                altura = float(request.POST['altura']) / 100  # Convertir a metros
                peso = float(request.POST['peso'])
                imc = peso / (altura * altura)  # Calcular el IMC
                notas = request.POST.get('notas', '')
                temperatura = request.POST.get('temperatura')
                p_sistolica = request.POST.get('p_sistolica')
                p_diastolica = request.POST.get('p_diastolica')
                diagnostico = request.POST.get('diagnostico')
                sintomas = request.POST.get('sintomas')
                observaciones = request.POST.get('observaciones', '')  # Obtén las observaciones
                examenes_seleccionados = request.POST.getlist('examenes')  # Obtén los exámenes seleccionados
                recomendaciones = request.POST.get('recomendaciones', '')

                consulta = Consulta.objects.create(
                    hora_medica=hora,  # Asocia la consulta con la hora médica
                    temperatura=temperatura,
                    p_sistolica=p_sistolica,
                    p_diastolica=p_diastolica,
                    altura=altura,
                    peso=peso,
                    imc=imc,
                    notas=notas,
                    diagnostico=diagnostico,
                    sintomas=sintomas,
                    observaciones=observaciones,
                    estado='Iniciada'  # O el estado que desees
                )

                # Guardar medicamentos seleccionados
                if medicamentos_seleccionados:
                    consulta.had_receta=True
                    for medicamento in medicamentos_seleccionados:
                        via = request.POST.get(f'via_{medicamento.id}')
                        dosis = request.POST.get(f'dosis_{medicamento.id}')
                        frecuencia = request.POST.get(f'frecuencia_{medicamento.id}')
                        duracion = request.POST.get(f'duracion_{medicamento.id}')
                        Consulta_Receta.objects.create(
                            consulta=consulta,
                            medicamento=medicamento,
                            via=via,
                            dosis=dosis,
                            frecuencia=frecuencia,
                            duracion=duracion
                        )

                # Verificar si la sección de exámenes está activa
                if request.POST['exams_activa'] == 'true':
                    if examenes_seleccionados:  # Verifica si se seleccionaron exámenes
                        consulta.had_OrdExams = True
                        for examen_id in examenes_seleccionados:
                            examen = Examen.objects.get(pk=examen_id)
                            Consulta_Examen.objects.create(consulta=consulta, examen=examen, estado='solicitado')

                # Verificar si la sección de la licencia médica está activa
                if request.POST['licencia_activa'] == 'true':
                    # Validar los campos de la licencia médica
                    if not all([request.POST['lugar_emision'], request.POST['dirigido_a'], request.POST['email_empleador'], request.POST['antecedentes'], request.POST['diagnosis'], request.POST['inicio'], request.POST['termino']]):
                        messages.error(request, "Por favor, complete todos los campos de la licencia médica.")
                        return redirect('A31_Con:consulta_iniciar', hora_id=hora_id)

                    # Crear el objeto Consulta_Certificado
                    Consulta_Certificado.objects.create(
                        consulta=consulta,
                        lugar_emision=request.POST['lugar_emision'],

templates/A31_Con/consulta_detalle.html
{% extends 'base.html' %}

{% block content %}



<br>
<h1>Detalle de la Consulta</h1>
<hr>
<p><strong>N° Atención:</strong> {{ consulta.id }}</p>
<p><strong>Fecha:</strong> {{ consulta.hora_medica.f_hra }}</p>
<p><strong>Paciente:</strong> {{ consulta.hora_medica.paciente.user.first_name }} {{ consulta.hora_medica.paciente.user.last_name }}</p>
<p><strong>Médico:</strong> {{ consulta.hora_medica.medico.user.first_name }} {{ consulta.hora_medica.medico.user.last_name }}</p>
<p><strong>Temperatura:</strong> {{ consulta.temperatura }}</p>
<p><strong>Presión Sistólica:</strong> {{ consulta.p_sistolica }}</p>
<p><strong>Presión Diastólica:</strong> {{ consulta.p_diastolica }}</p>
<p><strong>Altura:</strong> {{ consulta.altura }}</p>
<p><strong>Peso:</strong> {{ consulta.peso }}</p>
<p><strong>IMC:</strong> {{ consulta.imc }}</p>
<p><strong>Síntomas:</strong> {{ consulta.sintomas }}</p>
<p><strong>Diagnóstico:</strong> {{ consulta.diagnostico }}</p>
<p><strong>Observaciones:</strong> {{ consulta.observaciones }}</p>

<br>
<h2>Exámenes Solicitados</h2>
<hr>
<ul>
    {% for examen in consulta.consulta_examenes.all %}
        <li>{{ examen.examen.nombre }} - {{ examen.estado }}
            {% if examen.archivo %}
                <a href="{{ examen.archivo.url }}" target="_blank">Ver archivo</a>
                {% if not consulta.resultados_enviados %}
                    {% for group in request.user.groups.all %}
                        {% if group.name == "Pacientes" %}
                            <a href="{% url 'A31_Con:bajar_resultado_examen' examen.id %}">Bajar archivo </a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% else %}
                {% if not consulta.resultados_enviados %}
                    {% for group in request.user.groups.all %}
                        {% if group.name == "Pacientes" %}
                            <a href="{% url 'A31_Con:subir_resultado_examen' examen.id %}">Subir archivo</a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
</ul>

{% if todos_examenes_subidos and not consulta.resultados_enviados %}
    <form method="post" action="{% url 'A31_Con:enviar_resultados_al_medico' consulta.id %}">
        {% csrf_token %}
        <button type="submit" class="btn but-go">Enviar Resultados al Médico</button>
    </form>
{% elif consulta.resultados_enviados %}
    <button type="button" class="btn btn-secondary" disabled>Resultados Enviados al Médico</button>
{% endif %}


<br><br>
<h2>Medicamentos Prescritos</h2>
<hr>
<ul>
    {% for receta in consulta.consulta_recetas.all %}
    <li>{{ receta.medicamento.nombre_gen }} ({{ receta.medicamento.nombre_com }}) - Vía: {{ receta.via }}, Dosis: {{ receta.dosis }}, Frecuencia: {{ receta.frecuencia }}, Duración: {{ receta.duracion }}</li>
    {% endfor %}
</ul>

<br>
<h2>Certificado Médico</h2>
<hr>
<p><strong>Lugar de Emisión:</strong> {{ consulta.consulta_certificados.first.lugar_emision }}</p>
<p><strong>Dirigido a:</strong> {{ consulta.consulta_certificados.first.dirigido_a }}</p>
<p><strong>Email empleador:</strong> {{ consulta.consulta_certificados.first.email_empleador }}</p>
<p><strong>Antecedentes:</strong> {{ consulta.consulta_certificados.first.antecedentes }}</p>
<p><strong>Diagnóstico:</strong> {{ consulta.consulta_certificados.first.diagnosis }}</p>
<p><strong>Recomendaciones:</strong> {{ consulta.consulta_certificados.first.recomendaciones }}</p>
<p><strong>Inicio:</strong> {{ consulta.consulta_certificados.first.inicio }}</p>
<p><strong>Término:</strong> {{ consulta.consulta_certificados.first.termino }}</p>

<br>
<h2>Imágenes</h2>
<hr>
<ul>
    {% if imagenes %}
        {% for imagen in imagenes %}
            <li>
                {% if imagen.imagen %}
                    <img src="{{ imagen.imagen.url }}" alt="Imagen de consulta" style="max-width: 200px;">
                    <p>{{ imagen.diagnostico }}</p>
                {% endif %}
            </li>
        {% endfor %}
    {% else %}
        <p> No hay imágenes disponibles. </p>
    {% endif %}
</ul>

<br>
<h2>Baja tus documentos</h2>
<hr>
<p class="d-inline-flex gap-1">
    <a href="{% url 'A31_Con:imprimir_orden_examen' consulta.id %}" class="btn btn-primary"><i class="bi bi-printer-fill"> &nbsp; Orden de Exámenes</i></a>
    <a href="{% url 'A31_Con:imprimir_prescripcion' consulta.id %}" class="btn btn-primary"><i class="bi bi-printer-fill"> &nbsp; Prescripción</i></a>
    <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary">Certificado Médico</button>
        <a href="{% url 'A31_Con:imprimir_certificado' consulta.id %}" class="btn btn-primary"><i class="bi bi-printer-fill"></i></a>
        <form method="post" action="{% url 'A31_Con:enviar_email_certificado' consulta.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary"><i class="bi bi-envelope-arrow-up-fill"></i></button>
        </form>
    </div>
    <a href="{% url 'A31_Con:consultas' %}" class="btn but-go"><i class="bi bi-arrow-counterclockwise"> &nbsp; Volver</i></a>
    {% comment %} <button class="btn btn-secondary" onclick="enviarEmailCertificado({{ consulta.id }})">Enviar Certificado por Email</button> {% endcomment %}
</p>



<script>
function enviarEmailCertificado(consultaId) {
    fetch(`/enviar_email_certificado/${consultaId}/`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
        },
        body: JSON.stringify({ consulta_id: consultaId })
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            alert('Certificado enviado por email exitosamente.');
        } else {
            alert('Error al enviar el certificado por email.');
        }
    })
    .catch(error => {
        console.error('Error:', error);
        alert('Error al enviar el certificado por email.');
    });
}
</script>

{% endblock %}

templates/A31_Con/consulta_informes.html
{% extends 'base.html' %}
{% block content %}
<h1>Informes de Pacientes</h1>
<table id="example" class="table table-bordered border-primary table-success table-hover" >
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Cédula</th>
            <th>F. Nacimiento</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in pacientes %}
            <tr>
                <td>{{ paciente.user.get_full_name }}</td>
                <td>{{ paciente.user.dni}}</td>
                <td>{{paciente.user.f_nacim}}</td>
                <td>
                    <a class="btn but-go" href="{% url 'A31_Con:informe_historico' paciente.user.id %}">Informe Histórico</a>
                    <a class="btn but-go" href="{% url 'A31_Con:consultas_resumen' paciente.user.id %}">Consultas</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/A31_Con/consultas.html
{% extends 'base.html' %}

{% block content %}
<h1>Listado de Consultas Médicas</h1>

<div class="d-flex justify-content-center">
    <div id="spinner" class="spinner-border text-danger" role="status" style="display: none;">
        <span class="visually-hidden">Loading...</span>
    </div>
</div>

<div id="contenido_principal"></div>  </div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script> <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function() {
        $("#spinner").show();

        $.ajax({
            url: '/consultas/consultas_ajax/',
            type: 'GET',
            success: function(data) {
                $("#spinner").hide();
                $("#contenido_principal").html(data.html);

                // Inicializar DataTables después de cargar el contenido
                $('#example').DataTable({
                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/1.13.6/i18n/es-ES.json"
                    },
                    // Opciones adicionales de DataTables si las necesitas
                    // Por ejemplo:
                    // "paging": false, // Deshabilitar la paginación
                    // "searching": false, // Deshabilitar la búsqueda
                    // "info": false, // Deshabilitar la información de "Mostrando X de Y entradas"
                });
            },
            error: function(xhr, status, error) {
                console.error("Error AJAX:", status, error);
                $("#spinner").hide();
                $("#contenido_principal").html("<p>Error al cargar los datos.</p>");
            }
        });
    });
</script>

{% endblock %}

templates/A31_Con/consultas_ajax.html
<table id="example" class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Fecha/Hora</th>
            <th>Médico</th>
            <th>Paciente</th>
            {% comment %} <th>Temp.</th>
            <th>P. Sist.</th>
            <th>P. Diast.</th>
            <th>Altura</th>
            <th>Peso</th>
            <th>IMC</th> {% endcomment %}
            {% comment %} <th>Síntomas</th>
            <th>Diagnóstico</th> {% endcomment %}
            <th>Estado</th>
            <th>Acciones</th> </tr>
    </thead>
    <tbody>
        {% for consulta in consultas %}
        <tr>
            <td>{{ consulta.id }}</td>
            <td>{{ consulta.hora_medica.f_hra }}</td>
            <td>{{ consulta.hora_medica.medico.user.first_name }} {{ consulta.hora_medica.medico.user.last_name }}</td>
            <td>{% if consulta.hora_medica.paciente %}{{ consulta.hora_medica.paciente.user.first_name }} {{ consulta.hora_medica.paciente.user.last_name }}{% endif %}</td>
            {% comment %} <td>{{ consulta.temperatura }}</td>
            <td>{{ consulta.p_sistolica }}</td>
            <td>{{ consulta.p_diastolica }}</td>
            <td>{{ consulta.altura }}</td>
            <td>{{ consulta.peso }}</td>
            <td>{{ consulta.imc }}</td> {% endcomment %}
            {% comment %} <td>{{ consulta.sintomas }}</td>
            <td>{{ consulta.diagnostico }}</td> {% endcomment %}
            <td>{{ consulta.estado }}</td>
            <td>
                <div class="d-grid gap-2 d-md-block">
                    <a href="{% url 'A31_Con:consulta_detalle' consulta.id %}" class="btn but-go" role="button">Ver Ficha</a>
                    {% comment %} <a href="" class="btn btn-sm btn-outline-warning">Subir Resultados</a> {% endcomment %}
                    {% comment %} <a href="{% url 'A31_Con:consulta_editar' consulta.id %}" class="btn btn-sm btn-outline-success">Editar/Cerrar</a> {% endcomment %}
                    {% if consulta.resultados_enviados %}
                        <a href="{% url 'A31_Con:consulta_editar' consulta.id %}" class="btn but-add">Editar/Cerrar</a>
                    {% endif %}
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/A31_Con/consultas_resumen.html
{% extends 'base.html' %}
{% block content %}
<h1>Resumen de Consultas de {{ paciente.user.get_full_name }}</h1>
<table id="example" class="table table-bordered border-primary table-success table-hover" >
    <thead>
        <tr>
            <th>Consulta Id</th>
            <th>Fecha</th>
            <th>Estado</th>
            <th> Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for consulta in consultas %}
            <tr>
                <td>{{ consulta.id }}</td>
                <td>{{consulta.hora_medica.f_hra}}</td>
                <td>{{consulta.estado}}</td>
                <td>
                    <a class="btn but-go" href="{% url 'A31_Con:consulta_detalle' consulta.id %}">Ver Consulta</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/A31_Con/detalle_consulta.html
{% extends 'base.html' %}
{% block content %}
<h1>Detalle de la Consulta</h1>
<p><strong>Paciente:</strong> {{ consulta.hora_medica.paciente.user.get_full_name }}</p>
<p><strong>Diagnóstico:</strong> {{ consulta.diagnostico }}</p>
<p><strong>Notas:</strong> {{ consulta.notas }}</p>

<h2>Recetas</h2>
<ul>
    {% for receta in recetas %}
        <li>{{ receta.medicamento.nombre_com }} - {{ receta.dosis }} - {{ receta.frecuencia }} - {{ receta.duracion }}</li>
    {% endfor %}
</ul>

<h2>Exámenes</h2>
<ul>
    {% for examen in examenes %}
        <li>{{ examen.examen.nombre }} - {{ examen.estado }}
            {% if examen.archivo %}
                <a href="{{ examen.archivo.url }}" target="_blank">Ver archivo</a>
            {% else %}
                <a href="{% url 'subir_resultado_examen' examen.id %}">Subir resultado</a>
            {% endif %}
        </li>
    {% endfor %}
</ul>

<h2>Certificados</h2>
<ul>
    {% for certificado in certificados %}
        <li>{{ certificado.archivo.name }}</li>
    {% endfor %}
</ul>

<h2>Imágenes</h2>
<ul>
    {% for imagen in imagenes %}
        <li>
            {% if imagen.imagen %}
                <img src="{{ imagen.imagen.url }}" alt="Imagen de consulta" style="max-width: 200px;">
            {% endif %}
            <p>{{ imagen.diagnostico }}</p>
        </li>
    {% endfor %}
</ul>
{% endblock %}

templates/A31_Con/imprimir_orden_examen.html
<!DOCTYPE html>
<html>
<head>
    <title>Orden de Exámenes</title>
</head>
<body>
    <h1>Orden de Exámenes</h1>

    <p><strong>Paciente:</strong> {{ consulta.hora_medica.paciente.user.first_name }} {{ consulta.hora_medica.paciente.user.last_name }}</p>
    <p><strong>Médico:</strong> {{ consulta.hora_medica.medico.user.first_name }} {{ consulta.hora_medica.medico.user.last_name }}</p>
    <p><strong>Fecha:</strong> {{ consulta.hora_medica.f_hra }}</p>

    <h2>Exámenes Solicitados</h2>
    <ul>
        {% for examen in consulta.consulta_examenes.all %}
        <li>{{ examen.examen.nombre }}</li>
        {% endfor %}
    </ul>

    <h2>Observaciones</h2>
    <p>{{ consulta.observaciones }}</p>

    <p>Firma del Médico:</p>
</body>
</html>

templates/A31_Con/informe_historico.html
{% extends 'base.html' %}
{% block content %}
<h1>Historial Médico de {{ paciente.user.get_full_name }}</h1>
<hr>
<h2>Datos y Predicciones</h2>
<div id="contenedorGrafico" style="width: 100%; height: 50%vw;">
    <img src="data:image/png;base64,{{ grafico_presiones }}" alt="Gráfico de presiones">
</div>
<p><strong>{{ comentarios }}</strong></p>

<h2>Últimos Diagnósticos</h2>
<ul>
    {% for consulta in ultimos_diagnosticos %}
        <li>Consulta N° {{consulta.id}}-[{{ consulta.hora_medica.f_hra }}]: {{ consulta.diagnostico }}</li>
    {% endfor %}
</ul>

<h2>Exámenes Pendientes</h2>
{% if examenes_pendientes %}
    <ol>
        {% for examen in examenes_pendientes %}
            {% if examen.estado != 'perdida' %}<li>Orden de Examen N°: {{examen.consulta.id}}-{{ examen.examen.nombre }}</li>{% endif %}
        {% endfor %}
    </ol>
{% else %}
    <p>No hay exámenes pendientes.</p>
{% endif %}




{% endblock %}

templates/A31_Con/subir_resultado_examen.html
{% extends 'base.html' %}
{% block content %}
<h1>Subir Resultado de Examen</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="archivo">Archivo del Examen:</label>
    <input type="file" name="archivo" required>
    <button type="submit">Subir</button>
</form>
{% endblock %}