A10_Usu/urls.py
from django.urls import path
from .views import *
# from django.views.generic import LogoutView

app_name = 'A10_Usu'

urlpatterns = [
    path('', home, name='home'),
    path('registro_paciente/', registro_paciente, name='registro_paciente'),
    path('mensaje_verificacion_enviado/', mensaje_verificacion_enviado, name='mensaje_verificacion_enviado'),
    path('verificar_cuenta/<str:uidb64>/<str:token>/', verificar_cuenta, name='verificar_cuenta'),
    path('completar_perfil_paciente/<int:paciente_id>/', completar_perfil_paciente, name='completar_perfil_paciente'),
    path('listar_pacientes/', listar_pacientes, name='listar_pacientes'),

    path('usuarios/', usuarios, name='usuarios'),
    path('registro_usuario/', registro_usuario, name='registro_usuario'),
    path('completar_perfil_jefe_plataforma/<int:jefe_plataforma_id>/', completar_perfil_jefe_plataforma, name='completar_perfil_jefe_plataforma'),
    path('completar_perfil_recepcionista/<int:recepcionista_id>/', completar_perfil_recepcionista, name='completar_perfil_recepcionista'),
    path('completar_perfil_medico/<int:medico_id>/', completar_perfil_medico, name='completar_perfil_medico'),
    path('ver_perfilout/<int:user_id>/', ver_perfilout, name='ver_perfilout'),
    # path('registro_jefe_plataforma/', registro_jefe_plataforma, name='registro_jefe_plataforma'),
    # path('registro_recepcionista/', registro_recepcionista, name='registro_recepcionista'),

    path('cambiar_rol/',cambiar_rol,name='cambiar_rol'),

    path('vista_parametros/', vista_parametros, name='vista_parametros'),
    path('registro_genero/', registro_genero, name='registro_genero'),
    path('registro_especialidad', registro_especialidad, name='registro_especialidad'),
    path('registro_sistema_salud/', registro_sistema_salud, name='registro_sistema_salud'),
    path('registroExamen/', registroExamen, name='registroExamen'),
    path('registroMedicamento/', registroMedicamento, name='registroMedicamento'),
    path('medicamento/<int:pk>/', medicamentoVer, name='medicamentoVer'),
    path('medicamento/editar/<int:pk>/', medicamentoEditar, name='medicamentoEditar'),

]

Med/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from A10_Usu.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),

    path('accounts/', include('allauth.urls')),

    # path('accounts/signup/paciente/', registro_paciente, name='registro_paciente'),
    # path('accounts/signup/registro_jefe_plataforma/',registro_jefe_plataforma, name='registro_jefe_plataforma'),

    path('accounts/redireccion_despues_login/', redireccion_despues_login, name='redireccion_despues_login'),
    path('accounts/seleccionar_tipo_registro/', seleccionar_tipo_registro, name='seleccionar_tipo_registro'),

    path('accounts/completar_perfil_paciente/', completar_perfil_paciente, name='completar_perfil_paciente'),
    # path('accounts/email-confirmation/<key>/', CustomConfirmEmailView.as_view(), name='account_confirm_email'),
    # path('accounts/completar_perfil_jefe_plataforma/', completar_perfil_jefe_plataforma, name='completar_perfil_jefe_plataforma'),


    # path('accounts/signup/recepcionista/', registro_recepcionista, name='registro_recepcionista'),
    # path('accounts/signup/medico/', registro_medico, name='registro_medico'),
    path('gestion_usuarios/', include('A10_Usu.urls', namespace='Usuarios')),
    path('horas_medicas/', include('A20_Hrs.urls', namespace='Horas Medicas')),
    path('fichas_medicas/', include('A30_Fic.urls',namespace='Fichas Medicas')),
    path('consultas/', include('A31_Con.urls',namespace='Consultas')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="es" class="h-100">

{% comment %} {% load static %} {% endcomment %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HumanaSalud</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sticky-footer-navbar/">
            <!-- Bootstrap core CSS -->
        <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <!-- Bootstrap CSS -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        {% comment %} {% block extra_head %}{% endblock %} {% endcomment %}
        <!-- Bootstrap core CSS -->
        {% comment %} <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> {% endcomment %}
        {% comment %} <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> {% endcomment %}
        <!-- CSS del CDN de IconBootstrap -->
        {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"> {% endcomment %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7rxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">

        <!--  CSS del CDN del DataTable  -->
        <link href="https://cdn.datatables.net/1.13.5/css/dataTables.bootstrap5.min.css" rel="stylesheet"/>
        <link href="https://cdn.datatables.net/buttons/2.4.0/css/buttons.bootstrap5.min.css" rel="stylesheet"/>

        <!-- SELECT2 -->
        {% comment %} <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" /> {% endcomment %}

        <!-- Custom styles for this template -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

        <!-- Custom styles for this template -->
        <link href="sticky-footer-navbar.css" rel="stylesheet">

        {% block extrahead %}{% endblock %}


        <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }
        }

        </style>



    </head>

<!-- ############################BODY#############################-->

    <body class="d-flex flex-column h-100">

        <header>
            <!-- Fixed navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-secondary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home' %}">HumanaSalud</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'A10_Usu:cambiar_rol' %}">Cambiar Rol</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'A10_Usu:ver_perfilout' user.id %}" tabindex="-1" aria-disabled="true">Tu perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'account_logout' %}" tabindex="-1" aria-disabled="true">Salir</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}" tabindex="-1" aria-disabled="true">Ingresar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'A10_Usu:registro_paciente' %}" tabindex="-1" aria-disabled="true">Registro Pacientes</a>
                            </li>
                            {% endif %}
                        </ul>
                    {% comment %} <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                        </form> {% endcomment %}
                    </div>
                </div>
            </nav>
        </header>

        <main>
            <!-- Cartelera de Mensajes -->
            <hr>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <hr>



            <div class="container-fluid m-2">
                {% block content %}
                    {# AQUÍ VA EL CODIGO DE CADA VISTA #}
                {% endblock %}
            </div>




            <hr>
            <!-- Footer -->
            <footer class="container">
                <p class="">&copy; 2025 HumanaSalud &middot; <a href="#">Privacidad</a> &middot; <a href="#">Términos</a></p>
                <p class="float-end"><a href="#">Volver al inicio</a></p>
            </footer>
        </main>


        <!-- Bootstrap JS and dependencies -->
        {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script> {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        {% comment %} <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> {% endcomment %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <!-- jQuery y DataTable -->
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>  </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
        <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/2.4.0/js/dataTables.buttons.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/2.4.0/js/buttons.bootstrap5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/2.4.0/js/buttons.colVis.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/2.4.0/js/buttons.html5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/2.4.0/js/buttons.print.min.js"></script>

        {% comment %} <!-- Select2 -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script> {% endcomment %}

        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

        <!-- Chartjs para hacer gráficos-->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/moment"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment"></script>

        {% block extrajs %}
        <script>
            $(document).ready(function() {
                $('#example').DataTable();
            });
        </script>
        {% endblock %}

    </body>
</html>